abstract: A Data Driven Testing Framework
author: "Ingy d\xC3\xB6t Net <ingy@cpan.org>"
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: Test-Base
no_index: 
  directory: 
    - inc
    - t
requires: 
  Filter::Util::Call: 0
  Spiffy: 0.30
  Test::More: 0.62
  perl: 5.6.1
version: 0.54
